slider_config:
  label: 轮播配置
  items:
    slider_main_enable:
       name: slider_main_enable
       label: 轮播开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    slider_main_model:
       name: slider_main_model
       label: 轮播模式
       type: select
       default: json
       options:
         - value: json
           label: JSON模式
         - value: tag
           label: 标签模式
       description: 'JSON操作可用<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>'
    slider_main_json_content:
       name: slider_main_json_content
       label: 轮播列表JSON内容
       type: textarea
       placeholder: '请参考下方JSON格式'
       description: '格式：[{"id":0,"cate":"类型","title":"标题","thumbnail":"图片链接","url":"跳转连接","author":"作者","authorUrl":"作者头像","createTime":"日期"}]'
       default: '[{"id":0,"cate":"测试轮播","title":"JSON测试轮播效果0","thumbnail":"https://www.mumusur.com/themes/liem_lmumusur/source/picture/140bd62c252b83-imageresizem_fill1.jpg","url":"http://baidu.com","author":"里哥","authorUrl":"https://www.mumusur.com/avatar","createTime":"2018-12-11"},{"id":1,"cate":"测试轮播","title":"JSON测试轮播效果1","thumbnail":"https://www.mumusur.com/themes/liem_lmumusur/source/picture/130cd5cd602253-imageresizem_fill1.jpg","url":"http://baidu.com","author":"里哥","authorUrl":"https://www.mumusur.com/avatar","createTime":"2018-12-11"}]'
    slider_side_json_content:
       name: slider_side_json_content
       label: 轮播附图JSON内容
       type: textarea
       placeholder: '请参考下方JSON格式'
       description: '格式：{"id":0,"cate":"类型","title":"标题","thumbnail":"图片链接","url":"跳转连接","author":"作者","authorUrl":"作者头像","createTime":"日期"}'
       default: '{"id":0,"cate":"测试轮播","title":"JSON测试轮播附图效果","thumbnail":"https://www.mumusur.com/themes/liem_lmumusur/source/picture/159aa39ad7fbd7-imageresizem_fill1.jpg","url":"http://baidu.com","author":"里哥","authorUrl":"https://www.mumusur.com/avatar","createTime":"2018-12-11"}'
    slider_main_tag_content:
       name: slider_main_tag_content
       label: 轮播列表标签别名
       type: text
       placeholder: '默认为lunboliebiao'
       description: '自定义轮播图显示内容，对应文章标签别名,建议是英文字母'
    slider_side_tag_content:
       name: slider_side_tag_content
       label: 轮播附图标签别名
       type: text
       placeholder: '默认为lunbofutu'
       description: '自定义右侧图显示内容，对应文章标签别名,建议是英文字母'
    slider_list_enable:
       name: slider_list_enable
       label: 列表开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    slider_list_model:
       name: slider_list_model
       label: 显示模式
       type: select
       default: json
       options:
         - value: json
           label: JSON模式
         - value: tag
           label: 标签模式
       description: 'JSON操作可用<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>'
    slider_list_json_content:
       name: slider_list_json_content
       label: 轮播列表JSON内容
       type: textarea
       placeholder: '请参考下方JSON格式'
       description: '格式：[{"id":0,"cate":"类型","title":"标题","thumbnail":"图片链接","url":"跳转连接","author":"作者","authorUrl":"作者头像","createTime":"日期"}]'
       default: '[{"id":0,"cate":"测试轮播","title":"JSON测试轮播效果0","thumbnail":"https://www.mumusur.com/themes/liem_lmumusur/source/picture/41475962a1e20195a_1_cover-imager2.jpg","url":"http://baidu.com","author":"里哥","authorUrl":"https://www.mumusur.com/avatar","createTime":"2018-12-11"},{"id":1,"cate":"测试轮播","title":"JSON测试轮播效果1","thumbnail":"https://www.mumusur.com/themes/liem_lmumusur/source/picture/140bd62c252b83-imageresizem_fill2.jpg","url":"http://baidu.com","author":"里哥","authorUrl":"https://www.mumusur.com/avatar","createTime":"2020-12-11"},{"id":2,"cate":"测试轮播","title":"JSON测试轮播效果2","thumbnail":"https://www.mumusur.com/themes/liem_lmumusur/source/picture/130cd5cd602253-imageresizem_fill2.jpg","url":"http://baidu.com","author":"里哥","authorUrl":"https://www.mumusur.com/avatar","createTime":"2019-12-11"},{"id":3,"cate":"测试轮播","title":"JSON测试轮播效果3","thumbnail":"https://www.mumusur.com/themes/liem_lmumusur/source/picture/159aa39ad7fbd7-imageresizem_fill2.jpg","url":"http://baidu.com","author":"里哥","authorUrl":"https://www.mumusur.com/avatar","createTime":"2018-02-11"}]'
    slider_list_tag_content:
       name: slider_list_tag_content
       label: 列表标签别名
       type: text
       placeholder: '默认为liebiao'
       description: '自定义显示内容，对应文章标签别名,建议是英文字母'
enable_config:
  label: 启停配置
  items: 
    profile_enable:
       name: profile_enable
       label: 博主信息
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    profile_banner_img:
       name: profile_banner_img
       label: 博主封面
       type: attachment
       placeholder: '博主封面图'
    hello_info_enable:
       name: hello_info_enable
       label: 问候模块
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    hello_title:
       name: hello_title
       label: 问候称呼
       type: text
       default: '嗨，朋友！'
    hello_content:
       name: hello_content
       label: 问候内容
       type: text
       default: '所有的伟大，都源于一个勇敢的开始'
    hot_post_enable:
       name: hot_post_enable
       label: 热门文章
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    recent_post_count:
       name: hot_post_count
       label: 热文条数
       type: text
       default: '5'
       description: '只能填数字，默认为5'
    recent_post_enable:
       name: recent_post_enable
       label: 最新文章
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    recent_post_count:
       name: recent_post_count
       label: 新文条数
       type: text
       default: '5'
       description: '只能填数字，默认为5'
    tag_cloud_enable:
       name: tag_cloud_enable
       label: 热门标签
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    recent_comment_enable:
       name: recent_comment_enable
       label: 最新留言
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    recent_comment_count:
       name: recent_comment_count
       label: 留言条数
       type: text
       default: '5'
       description: '只能填数字，默认为5'
    footer_links_enable:
       name: footer_links_enable
       label: 底部友链
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    footer_links_alias:
       name: footer_links_alias
       label: 友链别名
       type: text
       placeholder: '规则为匹配分组名，默认：友情链接'
social_config:
  label: 社交配置
  items:
    tool_qr_enable:
        name: qr_enable
        label: 二维码开关
        type: radio
        data-type: bool
        default: true
        options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    tool_qr_page_desc:
        name: tool_qr_page_desc
        label: 当前页描述
        type: text
        placeholder: '当前页二维码描述文字'
    tool_qr_01_img:
        name: tool_qr_01_img
        label: 二维码01图片
        type: attachment
        placeholder: '二维码01图片链接'
    tool_qr_01_desc:
       name: tool_qr_01_desc
       label: 二维码01描述
       type: text
       placeholder: '二维码01图片描述信息'
    tool_qr_02_img:
        name: tool_qr_02_img
        label: 二维码02图片
        type: attachment
        placeholder: '二维码02图片链接'
    tool_qr_02_desc:
       name: tool_qr_02_desc
       label: 二维码02描述
       type: text
       placeholder: '二维码02图片描述信息'
views_config:
  label: 界面配置
  items:
    header_links:
       name: header_links
       label: 头部链接
       type: textarea
       placeholder: '请参考下方JSON格式'
       description: '格式：[{id:编号,icon:"图标",name:"名称",url:"链接"}]'
       default: '[{id:0,icon:"",name:"公告",url:"https://mumusur.com"},{id:0,icon:"",name:"邀请码",url:"https://mumusur.com"},{id:0,icon:"b2font b2-vip",name:"成为会员",url:"https://mumusur.com"},{id:0,icon:"b2font b2-renzheng",name:"认证",url:"https://mumusur.com"}]'
    advert_enable:
       name: advert_enable
       label: 首页广告开关
       type: radio
       data-type: bool
       default: false
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    advert_title:
       name: advert_title
       label: Banner广告标题
       type: text
       placeholder: '广告标题'
    advert_pc_img:
       name: advert_pc_img
       label: BannerPC端广告图
       type: attachment
       placeholder: '广告图'
    advert_mobile_img:
       name: advert_mobile_img
       label: Banner移动端广告图
       type: attachment
       placeholder: '广告图'
    advert_href:
       name: advert_href
       label: Banner广告链接
       type: text
       placeholder: '广告链接'
       default: '#none'
    notice_enable:
       name: notice_enable
       label: 公告开关
       type: radio
       data-type: bool
       default: false
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    notice_tag:
       name: notice_tag
       label: 公告标签别名
       type: text
       placeholder: '默认为notice'
       description: '定义公告显示内容，对应文章标签别名,建议是英文字母'
    notice_navbar_enable:
       name: notice_navbar_enable
       label: 公告栏导航开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    notice_navbar:
       name: notice_navbar
       label: 公告栏导航代码
       type: textarea
       placeholder: '请输入代码'
       default: '<a href="https://www.mumusur.com/www/designer-navbar/index.html" target="_blank">
				     <i class="fas fa-paint-brush"></i>&nbsp;&nbsp;设计师导航网站
			     </a>
                 <a href="https://www.mumusur.com/journals" target="_blank">
				     <i class="fas fa-circle-o-notch fa-spin"></i>&nbsp;&nbsp;心情
			     </a>
                 <a href="https://www.mumusur.com/photos" target="_blank">
				     <i class="fas fa-photo"></i>&nbsp;&nbsp;图库
			     </a>
			     <a href="https://www.mumusur.com/s/about.html" target="_blank">
				     <i class="fas fa-coffee"></i>&nbsp;&nbsp;关于
			     </a>
          	     <a href="https://www.mumusur.com/s/guestbook.html" target="_blank">
				     <i class="fas fa-comments"></i>&nbsp;&nbsp;留言板
			     </a>'
footer_config:
  label: 页脚配置
  items:
    footer_logo:
      name: footer_logo
      label: 页脚LOGO
      type: attachment
      placeholder: '页脚LOGO'
      default: 'https://www.mumusur.com/upload/2020/3/logo2-b0d113f6a65b4b4280bef775e754d97f.png'
    footer_logo_memo:
      name: footer_logo_memo
      label: 页脚LOGO描述文字
      type: textarea
      placeholder: '页脚LOGO描述文字'
      default: '<p>一个热衷于分享各类资源的平台，本平台支持代劳代查寻资源服务，目前本平台均为人工回复，若有怠慢，望体谅！</p>
                <p>在线时间：10:00-17:00 22:00-24:00</p>
                <p>电子邮箱：996052600@qq.com</p>
                <p>私人微信：mumukerf</p>'
    footer_more_links:
      name: footer_more_links
      label: 链接集
      type: textarea
      placeholder: '链接集格式为json'
      description: '<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>格式复制：[{"id":0,"icon":"图标","title":"标题","url":"跳转连接"}]'
    footer_qr_01:
      name: footer_qr_01
      label: 二维码01
      type: attachment
      placeholder: '二维码01'
    footer_qr_01_desc:
       name: footer_qr_01_desc
       label: 二维码01描述
       type: text
       placeholder: '二维码01描述'
    footer_qr_02:
      name: footer_qr_02
      label: 二维码02
      type: attachment
      placeholder: '二维码02'
    footer_qr_02_desc:
       name: footer_qr_02_desc
       label: 二维码02描述
       type: text
       placeholder: '二维码02描述'
    footer_qr_03:
      name: footer_qr_03
      label: 二维码03
      type: attachment
      placeholder: '二维码03'
    footer_qr_03_desc:
       name: footer_qr_03_desc
       label: 二维码03描述
       type: text
       placeholder: '二维码03描述'
    footer_flinks_enable:
       name: footer_flinks_enable
       label: 页脚友情链接开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    footer_flinks_alias:
       name: footer_flinks_alias
       label: 匹配分组名
       type: text
       placeholder: '匹配分组名，默认友情链接'
    footer_flinks_name:
       name: footer_flinks_name
       label: 友链申请名
       type: text
       placeholder: '点击申请友链'
       default: '点击申请友链'
    footer_flinks_url:
       name: footer_flinks_url
       label: 友链申请地址
       type: text
       placeholder: '友链申请地址'
       default: 'https://www.mumusur.com/s/flinks.html'
    footer_desc_enable:
       name: footer_desc_enable
       label: 页脚描述开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    footer_desc:
       name: footer_desc
       label: 页脚描述
       type: textarea
       placeholder: '页脚描述信息(如版权信息)'