slider_01_set:
  label: 首页一屏
  items:
    slider_enable:
       name: notice_enable
       label: 轮播开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    slider_json_enable:
       name: slider_json_enable
       label: 轮播模式
       type: select
       default: json
       options:
         - value: json
           label: JSON模式
         - value: tag
           label: 标签模式
       description: '请使用<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>'
    slider_list_json_content:
       name: slider_json_content
       label: 轮播列表JSON内容
       type: textarea
       placeholder: '填入json格式[{id:int,title:string,thumbnail:String,url:string}]'
       description: '格式：[{"id":0,"title":"标题","thumbnail":"图片链接","url":"跳转连接"}]'
    slider_side_json_content:
       name: slider_json_content
       label: 轮播附图JSON内容
       type: textarea
       placeholder: '填入json格式[{id:int,title:string,thumbnail:String,url:string}]'
       description: '格式：[{"id":0,"title":"标题","thumbnail":"图片链接","url":"跳转连接"}]'
    slider_main_tag:
       name: slider_main_tag
       label: 轮播列表标签别名
       type: text
       placeholder: '默认为lunboliebiao'
       description: '自定义轮播图显示内容，对应文章标签别名,建议是英文字母'
    slider_right_tag:
       name: slider_right_tag
       label: 轮播附图标签别名
       type: text
       placeholder: '默认为lunbofutu'
       description: '自定义右侧图显示内容，对应文章标签别名,建议是英文字母'
slider_02_set:
  label: 首页二屏
  items:
    slider_enable:
       name: notice_enable
       label: 列表开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    slider_json_enable:
       name: slider_json_enable
       label: 显示模式
       type: select
       default: json
       options:
         - value: json
           label: JSON模式
         - value: tag
           label: 标签模式
       description: '请使用<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>'
    slider_list_json_content:
       name: slider_json_content
       label: 轮播列表JSON内容
       type: textarea
       placeholder: '填入json格式[{id:int,title:string,thumbnail:String,url:string}]'
       description: '格式：[{"id":0,"title":"标题","thumbnail":"图片链接","url":"跳转连接"}]'
    slider_main_tag:
       name: slider_main_tag
       label: 列表标签别名
       type: text
       placeholder: '默认为liebiao'
       description: '自定义显示内容，对应文章标签别名,建议是英文字母'
view_set:
  label: 界面配置
  items:
    advert_enable:
       name: advert_enable
       label: 首页广告开关
       type: radio
       data-type: bool
       default: false
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    advert_title:
       name: advert_title
       label: Banner广告标题
       type: text
       placeholder: '广告标题'
    advert_pc_img:
       name: advert_pc_img
       label: BannerPC端广告图
       type: attachment
       placeholder: '广告图'
    advert_mobile_img:
       name: advert_mobile_img
       label: Banner移动端广告图
       type: attachment
       placeholder: '广告图'
    advert_href:
       name: advert_href
       label: Banner广告链接
       type: text
       placeholder: '广告链接'
       default: '#none'
    notice_enable:
       name: notice_enable
       label: 公告开关
       type: radio
       data-type: bool
       default: false
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    notice_tag:
       name: notice_tag
       label: 公告标签别名
       type: text
       placeholder: '默认为notice'
       description: '定义公告显示内容，对应文章标签别名,建议是英文字母'
    notice_navbar_enable:
       name: notice_navbar_enable
       label: 公告栏导航开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    notice_navbar:
       name: notice_navbar
       label: 公告栏导航代码
       type: textarea
       placeholder: '请输入代码'
       default: '<a href="https://www.mumusur.com/www/designer-navbar/index.html" target="_blank">
				     <i class="fas fa-paint-brush"></i>&nbsp;&nbsp;设计师导航网站
			     </a>
                 <a href="https://www.mumusur.com/journals" target="_blank">
				     <i class="fas fa-circle-o-notch fa-spin"></i>&nbsp;&nbsp;心情
			     </a>
                 <a href="https://www.mumusur.com/photos" target="_blank">
				     <i class="fas fa-photo"></i>&nbsp;&nbsp;图库
			     </a>
			     <a href="https://www.mumusur.com/s/about.html" target="_blank">
				     <i class="fas fa-coffee"></i>&nbsp;&nbsp;关于
			     </a>
          	     <a href="https://www.mumusur.com/s/guestbook.html" target="_blank">
				     <i class="fas fa-comments"></i>&nbsp;&nbsp;留言板
			     </a>'
footer_set:
  label: 页脚配置
  items:
    footer_logo:
      name: footer_logo
      label: 页脚LOGO
      type: attachment
      placeholder: '页脚LOGO'
    footer_logo_memo:
      name: footer_logo_memo
      label: 页脚LOGO描述文字
      type: textarea
      placeholder: '页脚LOGO描述文字'
      default: '<p>一个资源丰富的平台</p>
                <p>在线时间：10:00-17:00 22:00-24:00</p>
                <p>电子邮箱：996052600@QQ.COM</p>'
    footer_more_links:
      name: footer_more_links
      label: 链接集
      type: textarea
      placeholder: '链接集格式为json'
      description: '<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>格式复制：[{"id":0,"icon":"图标","title":"标题","url":"跳转连接"}]'
    footer_qr_01:
      name: footer_qr_01
      label: 二维码01
      type: attachment
      placeholder: '二维码01'
    footer_qr_01_desc:
       name: footer_qr_01_desc
       label: 二维码01描述
       type: text
       placeholder: '二维码01描述'
    footer_qr_02:
      name: footer_qr_02
      label: 二维码02
      type: attachment
      placeholder: '二维码02'
    footer_qr_02_desc:
       name: footer_qr_02_desc
       label: 二维码02描述
       type: text
       placeholder: '二维码02描述'
    footer_qr_03:
      name: footer_qr_03
      label: 二维码03
      type: attachment
      placeholder: '二维码03'
    footer_qr_03_desc:
       name: footer_qr_03_desc
       label: 二维码03描述
       type: text
       placeholder: '二维码03描述'
    footer_flinks_enable:
       name: footer_flinks_enable
       label: 页脚友情链接开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    footer_flinks_alias:
       name: footer_flinks_alias
       label: 匹配分组名
       type: text
       placeholder: '匹配分组名，默认友情链接'
    footer_flinks_name:
       name: footer_flinks_name
       label: 友链申请名
       type: text
       placeholder: '点击申请友链'
       default: '点击申请友链'
    footer_flinks_url:
       name: footer_flinks_url
       label: 友链申请地址
       type: text
       placeholder: '友链申请地址'
       default: 'https://www.mumusur.com/s/flinks.html'
    footer_desc_enable:
       name: footer_desc_enable
       label: 页脚描述开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    footer_desc:
       name: footer_desc
       label: 页脚描述
       type: textarea
       placeholder: '页脚描述信息(如版权信息)'